'use client';

import { memo } from 'react';
import { BarChart3, Loader2 } from 'lucide-react';
import { HelpTooltip } from '@/components/common';
import type { CostSummary } from './types';

// ============================================================================
// Types
// ============================================================================

export interface UsageSummaryCardProps {
  summary: CostSummary | null;
  loading?: boolean;
  className?: string;
}

// ============================================================================
// MetricRow Component
// ============================================================================

function MetricRow({
  label,
  value,
  highlight = false,
  helpText,
}: {
  label: string;
  value: string;
  highlight?: boolean;
  helpText?: string;
}) {
  return (
    <div className="flex justify-between items-center py-2.5">
      <span className="flex items-center gap-1.5 text-sm text-slate-600 dark:text-slate-400">
        {label}
        {helpText && <HelpTooltip content={helpText} />}
      </span>
      <span
        className={`text-sm font-semibold ${
          highlight
            ? 'text-cyan-600 dark:text-cyan-400'
            : 'text-slate-900 dark:text-white'
        }`}
      >
        {value}
      </span>
    </div>
  );
}

// ============================================================================
// UsageSummaryCard Component
// ============================================================================

export const UsageSummaryCard = memo(({
  summary,
  loading = false,
  className = '',
}: UsageSummaryCardProps) => {
  // Loading state
  if (loading || !summary) {
    return (
      <div className={`bg-white dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700/50 overflow-hidden ${className}`}>
        <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700/30">
          <div className="flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-cyan-500" />
            <h3 className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Usage Summary</h3>
          </div>
        </div>
        <div className="p-4">
          <div className="flex flex-col items-center justify-center py-12">
            <Loader2 className="w-8 h-8 text-cyan-500 animate-spin mb-3" />
            <p className="text-sm text-slate-500 dark:text-slate-400">Loading usage data...</p>
          </div>
        </div>
      </div>
    );
  }

  const inputRatio = summary.total_tokens > 0
    ? (summary.input_tokens / summary.total_tokens) * 100
    : 50;
  const outputRatio = 100 - inputRatio;
  const tokenRatioDisplay = summary.output_tokens > 0
    ? (summary.input_tokens / summary.output_tokens).toFixed(1)
    : '0';

  return (
    <div className={`bg-white dark:bg-slate-800/60 rounded-xl border border-slate-200 dark:border-slate-700/50 overflow-hidden ${className}`}>
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700/30">
        <div className="flex items-center gap-2">
          <BarChart3 className="w-4 h-4 text-cyan-500" />
          <h3 className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Usage Summary</h3>
        </div>
      </div>
      <div className="p-4">
        <div className="divide-y divide-slate-100 dark:divide-slate-700/30">
          <MetricRow
            label="Total Tokens"
            value={`${(summary.total_tokens / 1000).toFixed(0)}K`}
            helpText="Tokens are the basic units AI models use to process text. 1 token ≈ 4 characters or ¾ of a word."
          />
          <MetricRow
            label="Cost per 1K Tokens"
            value={`$${summary.cost_per_1k_tokens.toFixed(4)}`}
            highlight
            helpText="Average cost to process 1,000 tokens. This varies by model - larger models cost more but provide better results."
          />
          <MetricRow
            label="Avg per Query"
            value={`${summary.avg_tokens_per_query.toLocaleString()} tokens`}
            helpText="Average number of tokens used per AI query, including both the question (input) and response (output)."
          />
          <MetricRow
            label="Cost per Query"
            value={`$${summary.avg_cost_per_query.toFixed(4)}`}
            helpText="Average cost of a single AI interaction. Lower is better, but complex queries naturally cost more."
          />
          <MetricRow
            label="Input Tokens"
            value={`${(summary.input_tokens / 1000).toFixed(0)}K`}
            helpText="Tokens sent to the AI model (your questions, context, system prompts). Usually cheaper than output tokens."
          />
          <MetricRow
            label="Output Tokens"
            value={`${(summary.output_tokens / 1000).toFixed(0)}K`}
            helpText="Tokens generated by the AI model (responses, analysis). Typically cost 3-5x more than input tokens."
          />
        </div>

        {/* Token ratio indicator */}
        <div className="mt-4 pt-4 border-t border-slate-200 dark:border-slate-700/30">
          <div className="flex justify-between text-xs text-slate-500 mb-1.5">
            <span className="flex items-center gap-1">
              Input/Output Ratio
              <HelpTooltip content="The ratio of input to output tokens. A higher ratio (e.g., 3:1) means you're sending more context than receiving responses, which is more cost-efficient." />
            </span>
            <span>{tokenRatioDisplay}:1</span>
          </div>
          <div className="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden flex">
            <div
              className="h-full bg-cyan-500"
              style={{ width: `${inputRatio}%` }}
            />
            <div
              className="h-full bg-purple-500"
              style={{ width: `${outputRatio}%` }}
            />
          </div>
          <div className="flex justify-between text-xs text-slate-500 mt-1">
            <span className="text-cyan-600 dark:text-cyan-400">Input</span>
            <span className="text-purple-600 dark:text-purple-400">Output</span>
          </div>
        </div>
      </div>
    </div>
  );
});

UsageSummaryCard.displayName = 'UsageSummaryCard';

export default UsageSummaryCard;
